--COMENTARIO
CREATE TABLE CJB4033071.DTASPERS(
    IDEPER  CHAR(18) NOT NULL,
    NOMPER  CHAR(40) NOT NULL,
    EDAPER  SMALLINT NOT NULL,
    GENPER  CHAR(1) DEFAULT 'X' NOT NULL,
    USRREG  CHAR(32) DEFAULT USER,
    FECREG  DATE DEFAULT CURRENT_DATE,
    USRMOD  CHAR(10) DEFAULT '',
    FECMOD  DATE DEFAULT '01-01-01',
    CONSTRAINT DTASPERS_PRIMARY_KEY PRIMARY KEY (IDEPER),
    CONSTRAINT DTASPERS_GENPER CHECK(GENPER IN ('M', 'F', 'X'))
)
RCDFMT RDTASPERS;

LABEL ON TABLE CJB4033071.DTASPERS IS 'DATOS DE PERSONA';

-- LABEL; Encabezado personalizado
LABEL ON COLUMN CJB4033071.DTASPERS (
    IDEPER TEXT IS 'IDENTIDAD',
    NOMPER TEXT IS 'NOMBRE',
    EDAPER TEXT IS 'EDAD',
    GENPER TEXT IS 'GENERO',
    USRREG TEXT IS 'USUARIO REGISTRO',
    FECREG TEXT IS 'FECHA REGISTRO',
    USRMOD TEXT IS 'USUARIO MODIFICO',
    FECMOD TEXT IS 'FECHA MODIFICACION'
);

--COMENTARIO; Descripcion tecnica
COMMENT ON COLUMN CJB4033071.DTASPERS (
    IDEPER IS 'NUMERO DE IDENTIDAD',
    NOMPER IS 'NOMBRE COMPLETO PERSONA',
    EDAPER IS 'EDAD DE LA PERSONA',
    GENPER IS 'GENERO M = MASCULINO, F = FEMENINO Y X = SIN ESPECIFICAR',
    USRREG IS 'USUARIO REGISTRO',
    FECREG IS 'FECHA REGISTRO',
    USRMOD IS 'USUARIO MODIFICO',
    FECMOD IS 'FECHA MODIFICACION'
);
