--COMENTARIO
CREATE TABLE CJB4033071/DTASPERS(
    IDEPER  CHAR(10) NOT NULL,
    NOMPER  CHAR(50) NOT NULL,
    EDAPER  DECIMAL(3,0) NOT NULL,
    GENPER  CHAR(1) DEFAULT 'X' NOT NULL,
    USRREG  CHAR(10) DEFAULT CURRENT_USER,
    FECREG  DATE DEFAULT CURRENT_DATE,
    USRMOD  CHAR(10) DEFAULT '',
    FECMOD  DATE DEFAULT '',
    CONSTRAINT DTASPERS_PRIMARY_KEY PRIMARY KEY (IDEPER)
    CONSTRAINT DTASPERS_GENPER CHECK(GENPER IN ('M', 'F', 'X'))
)
RCDFMT RDTASPERS;

